files:
  - source: /bundle/Resources/translations/ezplatform_fields_groups.en.xlf
    translation: /bundle/Resources/translations/ezplatform_fields_groups.%locale_with_underscore%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_content.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_content.%locale_with_underscore%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_content_type.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_content_type.%locale_with_underscore%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_language.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_language.%locale_with_underscore%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_role.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_role.%locale_with_underscore%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_section.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_section.%locale_with_underscore%.xlf
  - source: /bundle/Resources/translations/ezrepoforms_user_registration.en.xlf
    translation: /bundle/Resources/translations/ezrepoforms_user_registration.%locale_with_underscore%.xlf
  - source: /bundle/Resources/translations/validators.en.xlf
    translation: /bundle/Resources/translations/validators.%locale_with_underscore%.xlf
