services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\RepositoryForms\Form\Type\SwitcherType: ~

    EzSystems\RepositoryForms\Form\Type\FieldType\BinaryBaseFieldType: ~
