name: Browser tests

on:
    push:
        branches:
            - master
            - "[0-9]+.[0-9]+"
    pull_request: ~

jobs:
    core-web:
        name: "Core Web suite"
        uses: ezsystems/ezplatform/.github/workflows/callable-browser-tests.yaml@2.5
        with:
            test-suite: "--mode=standard --profile=repository-forms --non-strict"
            php-image: "ezsystems/php:7.1-v1"
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
